# Generated by Django 2.2.5 on 2019-09-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('make', models.CharField(max_length=150)),
                ('rengi', models.CharField(max_length=50)),
                ('veziyyeti', models.CharField(max_length=50)),
                ('yan_zede', models.CharField(max_length=150)),
                ('esas_zede', models.CharField(max_length=150)),
            ],
        ),
    ]
